REDDIT_CLIENT_ID = 'LLP_sf90snpflDPakifiSg'
REDDIT_CLIENT_SECRET = '-jnytqXk2V3K7bUe90TJa8NTE_VQ3Q'
REDDIT_USER_AGENT = 'PersonaScraperBot/0.1'

OPENAI_API_KEY = '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'
